import type { Metadata } from "next";
import { Geist, Geist_Mono, Roboto, Raleway } from "next/font/google";
import "./globals.css";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

const raleway = Raleway({
  weight: ["400", "500", "700"],
  variable: "--font-raleway",
  subsets: ["latin"],
})

const expandedOne = Roboto({
  weight: ["400", "500", "700"],
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${raleway.className} antialiased bg-background text-foreground`}
      >
        {children}
      </body>
    </html>
  );
}
