version: '3.9'

services:
  db:
    image: postgres:16-alpine
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    env_file:
      - ./.env

  backend:
    image: jfarce/barber-backend:latest
    restart: always
    expose:
      - "8080"   # Puerto expuesto internamente para Nginx
    depends_on:
      - db
    env_file:
      - ./.env

  frontend:
    image: jfarce/barber-frontend:latest
    restart: always
    expose:
      - "3000"   # Puerto expuesto internamente para Nginx
    depends_on:
      - backend

  nginx:
    image: nginx:stable-alpine
    ports:
      - "80:80"   # la app entera queda accesible en localhost:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - frontend
      - backend

volumes:
  pgdata:
