version: '3.9'

services:
  db:
    image: postgres:16-alpine
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    env_file:
      - ./.env

  backend:
    build:
      context: ./backend
    restart: always
    expose:
      - "8080" # Se expone el puerto internamente para que Nginx pueda comunicarse con él
    depends_on:
      - db
    env_file:
      - ./.env

  frontend:
    build:
      context: ./frontend
      args:
        NEXT_PUBLIC_API_BASE_URL: ${NEXT_PUBLIC_API_BASE_URL}
    restart: always
    expose:
      - "3000"
    depends_on:
      - backend
    env_file:
      - ./.env

  nginx:
    image: nginx:stable-alpine
    ports:
      - "80:80"   # la app entera queda accesible en localhost:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - frontend
      - backend

volumes:
  pgdata:
