version: '3.9'

services:
  db:
    image: postgres:16-alpine
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    env_file:
      - ./.env

  backend:
    build:
      context: ./backend
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - db
    env_file:
      - ./.env

  frontend:
    build:
      context: ./frontend
      args:
        NEXT_PUBLIC_API_BASE_URL: ${NEXT_PUBLIC_API_BASE_URL}
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - backend
    env_file:
      - ./.env

volumes:
  pgdata:
